<h1>Association Rule Mining com uso de algoritmo Apriori</h1>

T√©cnica super pr√°tica e muito usada em an√°lise de comportamento de clientes, <br>
carrinhos de compra, recomenda√ß√£o de produtos e descoberta de padr√µes.<br><br>

M√©todo de descobrir padr√µes e rela√ß√µes frequentes entre itens em grandes bases de dados.<br>
Muito aplicado em:<br>
<ul>
    <li>An√°lise de carrinho de compras ‚Üí market basket analysis</li>
    <li>Recomenda√ß√£o de produtos ‚Üí "quem compra X tende a comprar Y"</li>
    <li>Descoberta de comportamentos correlacionados em logs, sistemas, etc.</li>
</ul>
Como medir as regras - 3 m√©tricas principais:

<table border="1">
  <thead>
    <tr>
      <th>M√©trica</th>
      <th>Defini√ß√£o</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Support (suporte)</td>
      <td>Frequ√™ncia da regra no dataset</td>
    </tr>
    <tr>
      <td>Confidence (confian√ßa)</td>
      <td>Probabilidade de comprar Y dado que comprou X</td>
    </tr>
    <tr>
      <td>Lift </td>
      <td>Quantas vezes X e Y ocorrem juntos em rela√ß√£o ao esperado se fossem independentes<br>
          O Lift > 1 indica que X e Y ocorrem juntos mais frequentemente do que o esperado.
      </td>
    </tr>
  </tbody>
</table>
m√©todo de redu√ß√£o de dimensionalidade.<br>
Transforma um conjunto de vari√°veis correlacionadas em <br>
um novo conjunto de vari√°veis n√£o correlacionadas, <br>
chamadas de componentes principais.<br>
Esses componentes explicam a maior parte da vari√¢ncia dos dados, <br>
com o menor n√∫mero poss√≠vel de dimens√µes.<br>

O PCA ajuda voc√™ a simplificar dados complexos mantendo o m√°ximo de informa√ß√£o poss√≠vel.<br><br>

<h3>Algoritmo Apriori</h3>
‚úÖ O Apriori √© o algoritmo mais cl√°ssico e popular para gerar itemsets frequentes<br> 
‚Üí grupos de itens que aparecem juntos com suporte acima de um limiar m√≠nimo.<br>
‚úÖ Depois que voc√™ tem os itemsets frequentes, voc√™ gera as association rules com eles.<br>
‚úÖ O Apriori funciona de forma iterativa:<br><br>
1Ô∏è‚É£ Primeiro encontra os itens mais frequentes.<br>
2Ô∏è‚É£ Depois expande para pares frequentes.<br>
3Ô∏è‚É£ Depois para trios frequentes.<br>
4Ô∏è‚É£ E assim por diante ‚Äî sempre eliminando combina√ß√µes que n√£o atingem o suporte m√≠nimo <br>
(por isso o nome Apriori ‚Üí princ√≠pio de "se um subconjunto n√£o <br>
√© frequente, o conjunto maior tamb√©m n√£o ser√°").<br><br>

<h3>üöÄ Fluxo t√≠pico de uso:</h3>

1Ô∏è‚É£ Pr√©-processar dados ‚Üí tabela transacional (1 = item presente, 0 = item ausente)<br>
2Ô∏è‚É£ Rodar o Apriori ‚Üí obter os itemsets frequentes<br>
3Ô∏è‚É£ Gerar as regras de associa√ß√£o ‚Üí com suporte, confian√ßa e lift<br>
4Ô∏è‚É£ Analisar as regras ‚Üí filtrar as mais interessantes<br>
5Ô∏è‚É£ Aplicar no neg√≥cio ‚Üí recomenda√ß√£o, cross-selling, etc.

In [12]:
# ! pip install mlxtend

<h2>Iniciando o ambiente</h2>

In [22]:
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

<h2> Carregando o dataset de compras</h2>

In [24]:
data = pd.read_csv('groceries.csv')
#df.columns = ['Sepal_Length', 'Sepal_Width', 'Petal_Length', 'Petal_Width', 'Species']
data.head()

,1,2,3,4,5,6,7,8,9
0,citrus fruit,semi-finished bread,margarine,ready soups,NaN,NaN,NaN,NaN,NaN
1,tropical fruit,yogurt,coffee,NaN,NaN,NaN,NaN,NaN,NaN
2,whole milk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,pip fruit,yogurt,cream cheese,meat spreads,NaN,NaN,NaN,NaN,NaN
4,other vegetables,whole milk,condensed milk,long life bakery product,NaN,NaN,NaN,NaN,NaN

<h2> Convers√£o dos dados - Indica√ß√£o de todos os itens, sinalizando se foi comprado ou n√£o</h2>

In [26]:

basket_sets = pd.get_dummies(data)
basket_sets.head()

,1_Instant food products,1_UHT-milk,1_artif. sweetener,1_baby cosmetics,1_bags,1_baking powder,1_bathroom cleaner,1_beef,1_berries,1_beverages,...,9_sweet spreads,9_tea,9_vinegar,9_waffles,9_whipped/sour cream,9_white bread,9_white wine,9_whole milk,9_yogurt,9_zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

<h2>C√°lculo de Support </h2>

In [28]:
apriori(basket_sets, min_support=0.02)

     support    itemsets
0   0.030421         (7)
1   0.034951        (17)
2   0.029126        (23)
3   0.049191        (26)
4   0.064401        (47)
5   0.044660        (83)
6   0.024272        (90)
7   0.040453        (92)
8   0.038835        (99)
9   0.033981       (100)
10  0.076052       (105)
11  0.028803       (111)
12  0.044984       (123)
13  0.073463       (130)
14  0.022977       (131)
15  0.028803       (159)
16  0.058900       (217)
17  0.022977       (224)
18  0.040129       (232)
19  0.036893       (233)
20  0.031068       (243)
21  0.034628       (256)
22  0.062136       (263)
23  0.028479       (264)
24  0.045955       (351)
25  0.033010       (366)
26  0.024272       (378)
27  0.057929       (397)
28  0.023301       (398)
29  0.020712       (479)
30  0.024595       (497)
31  0.024272       (510)
32  0.033333       (531)
33  0.023301       (532)
34  0.020065       (631)
35  0.021036  (217, 397)

In [30]:
apriori(basket_sets, min_support=0.02, use_colnames=True)

     support                            itemsets
0   0.030421                            (1_beef)
1   0.034951                     (1_canned beer)
2   0.029126                         (1_chicken)
3   0.049191                    (1_citrus fruit)
4   0.064401                     (1_frankfurter)
5   0.044660                (1_other vegetables)
6   0.024272                       (1_pip fruit)
7   0.040453                            (1_pork)
8   0.038835                      (1_rolls/buns)
9   0.033981                 (1_root vegetables)
10  0.076052                         (1_sausage)
11  0.028803                            (1_soda)
12  0.044984                  (1_tropical fruit)
13  0.073463                      (1_whole milk)
14  0.022977                          (1_yogurt)
15  0.028803                    (2_citrus fruit)
16  0.058900                (2_other vegetables)
17  0.022977                       (2_pip fruit)
18  0.040129                      (2_rolls/buns)
19  0.036893                 (2_root vegetables)
20  0.031068                            (2_soda)
21  0.034628                  (2_tropical fruit)
22  0.062136                      (2_whole milk)
23  0.028479                          (2_yogurt)
24  0.045955                (3_other vegetables)
25  0.033010                      (3_rolls/buns)
26  0.024272                            (3_soda)
27  0.057929                      (3_whole milk)
28  0.023301                          (3_yogurt)
29  0.020712                (4_other vegetables)
30  0.024595                      (4_rolls/buns)
31  0.024272                            (4_soda)
32  0.033333                      (4_whole milk)
33  0.023301                          (4_yogurt)
34  0.020065                      (5_rolls/buns)
35  0.021036  (2_other vegetables, 3_whole milk)

In [52]:
frequent_itemsets = apriori(basket_sets, min_support=0.002, use_colnames=True)
frequent_itemsets['Length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
frequent_itemsets[frequent_itemsets['Length']>=3]

      support                                           itemsets  Length
820  0.002589    (3_other vegetables, 2_root vegetables, 1_beef)       3
821  0.002589      (1_chicken, 2_other vegetables, 3_whole milk)       3
822  0.002589  (2_other vegetables, 1_citrus fruit, 3_whole m...       3
823  0.003236    (1_citrus fruit, 2_tropical fruit, 3_pip fruit)       3
824  0.002589  (1_citrus fruit, 3_other vegetables, 4_whole m...       3
825  0.002265  (1_frankfurter, 6_whole milk, 5_other vegetables)       3
826  0.002265         (3_other vegetables, 4_whole milk, 1_pork)       3
827  0.003560  (1_root vegetables, 2_other vegetables, 3_whol...       3
828  0.002589                  (1_sausage, 2_rolls/buns, 3_soda)       3
829  0.002265      (1_sausage, 4_whole milk, 3_other vegetables)       3
830  0.002265      (5_whole milk, 1_sausage, 4_other vegetables)       3
831  0.002913  (2_other vegetables, 1_tropical fruit, 3_whole...       3
832  0.002265  (5_whole milk, 4_other vegetables, 2_citrus fr...       3
833  0.002265       (2_other vegetables, 3_whole milk, 4_butter)       3
834  0.003560         (2_other vegetables, 3_whole milk, 4_curd)       3
835  0.003883       (2_other vegetables, 3_whole milk, 4_yogurt)       3
836  0.002265   (2_other vegetables, 3_whole milk, 6_rolls/buns)       3
837  0.003236    (4_whole milk, 3_other vegetables, 2_pip fruit)       3
838  0.005825  (3_other vegetables, 4_whole milk, 2_root vege...       3
839  0.002265  (4_other vegetables, 2_tropical fruit, 3_pip f...       3
840  0.003560       (5_butter, 3_other vegetables, 4_whole milk)       3
841  0.002913       (5_yogurt, 4_whole milk, 3_other vegetables)       3
842  0.003560       (6_yogurt, 4_whole milk, 3_other vegetables)       3
843  0.002265  (4_root vegetables, 3_pip fruit, 5_other veget...       3
844  0.002265    (3_pip fruit, 6_whole milk, 5_other vegetables)       3
845  0.002589  (5_whole milk, 3_root vegetables, 4_other vege...       3
846  0.002913                   (5_yogurt, 3_whole milk, 4_curd)       3
847  0.003236  (4_root vegetables, 6_whole milk, 5_other vege...       3
848  0.002265       (7_butter, 6_whole milk, 5_other vegetables)       3

<h2>Regras de Associa√ß√£o</h2>

<h3>Confidence</h3>

In [58]:
rules = association_rules(frequent_itemsets, metric='confidence',   min_threshold=0.5)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(2_sausage),(1_frankfurter),0.011327,0.064401,0.011327,1.000000,15.527638,1.0,0.010597,inf,0.946318,0.175879,1.000000,0.587940
1,(7_pastry),(1_frankfurter),0.005178,0.064401,0.002589,0.500000,7.763819,1.0,0.002256,1.871197,0.875732,0.038647,0.465583,0.270101
2,(2_ham),(1_sausage),0.007120,0.076052,0.004531,0.636364,8.367505,1.0,0.003989,2.540858,0.886804,0.057613,0.606432,0.347969
3,(2_meat),(1_sausage),0.006796,0.076052,0.004854,0.714286,9.392097,1.0,0.004338,3.233819,0.899642,0.062241,0.690768,0.389058
4,(3_beef),(1_sausage),0.004854,0.076052,0.002589,0.533333,7.012766,1.0,0.002220,1.979889,0.861585,0.033058,0.494921,0.283688

<h3>Lift</h3>

In [62]:
rules = association_rules(frequent_itemsets, metric='lift', min_threshold=1)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(1_beef),(2_citrus fruit),0.030421,0.028803,0.005502,0.180851,6.278986,1.0,0.004625,1.185618,0.867117,0.102410,0.156558,0.185931
1,(2_citrus fruit),(1_beef),0.028803,0.030421,0.005502,0.191011,6.278986,1.0,0.004625,1.198508,0.865672,0.102410,0.165629,0.185931
2,(1_beef),(2_other vegetables),0.030421,0.058900,0.003236,0.106383,1.806173,1.0,0.001444,1.053136,0.460347,0.037594,0.050455,0.080664
3,(2_other vegetables),(1_beef),0.058900,0.030421,0.003236,0.054945,1.806173,1.0,0.001444,1.025950,0.474278,0.037594,0.025294,0.080664
4,(1_beef),(2_root vegetables),0.030421,0.036893,0.005502,0.180851,4.902016,1.0,0.004379,1.175741,0.820977,0.089005,0.149472,0.164987

<h3>Lift & Confidence</h3>

In [66]:
rules[(rules['lift']>=5) & (rules['confidence']>=0.5)]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
93,(2_sausage),(1_frankfurter),0.011327,0.064401,0.011327,1.000000,15.527638,1.0,0.010597,inf,0.946318,0.175879,1.000000,0.587940
136,(7_pastry),(1_frankfurter),0.005178,0.064401,0.002589,0.500000,7.763819,1.0,0.002256,1.871197,0.875732,0.038647,0.465583,0.270101
239,(2_ham),(1_sausage),0.007120,0.076052,0.004531,0.636364,8.367505,1.0,0.003989,2.540858,0.886804,0.057613,0.606432,0.347969
243,(2_meat),(1_sausage),0.006796,0.076052,0.004854,0.714286,9.392097,1.0,0.004338,3.233819,0.899642,0.062241,0.690768,0.389058
259,(3_beef),(1_sausage),0.004854,0.076052,0.002589,0.533333,7.012766,1.0,0.002220,1.979889,0.861585,0.033058,0.494921,0.283688
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
958,"(4_root vegetables, 6_whole milk)",(5_other vegetables),0.003883,0.012621,0.003236,0.833333,66.025641,1.0,0.003187,5.924272,0.988694,0.243902,0.831203,0.544872
959,"(4_root vegetables, 5_other vegetables)",(6_whole milk),0.005178,0.009385,0.003236,0.625000,66.594828,1.0,0.003188,2.641640,0.990111,0.285714,0.621447,0.484914
964,"(7_butter, 6_whole milk)",(5_other vegetables),0.002913,0.012621,0.002265,0.777778,61.623932,1.0,0.002229,4.443204,0.986646,0.170732,0.774937,0.478632
965,"(7_butter, 5_other vegetables)",(6_whole milk),0.002589,0.009385,0.002265,0.875000,93.232759,1.0,0.002241,7.924919,0.991842,0.233333,0.873816,0.558190
967,(7_butter),"(6_whole milk, 5_other vegetables)",0.004207,0.007443,0.002265,0.538462,72.341137,1.0,0.002234,2.150539,0.990343,0.241379,0.535000,0.421405

In [70]:
rules.iloc[778]

antecedents                 (7_whole milk)
consequents           (6_other vegetables)
antecedent support                0.004207
consequent support                 0.00712
support                           0.003883
confidence                        0.923077
lift                             129.65035
representativity                       1.0
leverage                          0.003854
conviction                       12.907443
zhangs_metric                     0.996479
jaccard                           0.521739
certainty                         0.922525
kulczynski                        0.734266
Name: 778, dtype: object